---@diagnostic disable: undefined-global, unused-local
-- autogenerated lush spec on Mon 30 Dec 2024 11:17:43 PM MSK
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv

-- GUI options
local bf, it, un = "bold", "italic", "underline"

local colors = {
  grays = {
    ["000"] = hsl("#000000"),
    ["050"] = hsl("#0E0E0E"),
    ["100"] = hsl("#1C1C1C"),
    ["150"] = hsl("#2A2A29"),
    ["200"] = hsl("#393837"),
    ["250"] = hsl("#474645"),
    ["300"] = hsl("#555453"),
    ["350"] = hsl("#636261"),
    ["400"] = hsl("#71706F"),
    ["450"] = hsl("#807F7D"),
    ["500"] = hsl("#8E8D8A"),
    ["550"] = hsl("#9C9B98"),
    ["600"] = hsl("#AAA9A6"),
    ["650"] = hsl("#B8B7B4"),
    ["700"] = hsl("#C6C5C2"),
    ["750"] = hsl(36, 6, 83),
    ["800"] = hsl(40, 10, 88),
    ["850"] = hsl(40, 18, 100),
    ["900"] = hsl(40, 100, 99),
  },
  green_pastel = hsl("#7FC784"),
  green_dark = hsl("#067D17"),
  white = hsl("#ffffff"),
  blue = hsl("#1750EB"),
  blue_pastel = hsl("#A6D2FF"),
  blue_light = hsl("#ADBEED"),
  orange_pastel = hsl("#F7E2CB"),
  orange_light = hsl("#fbb149"),
  orange_dark = hsl("#F58024"),
  yellow = hsl("#FFFC31"),
  purple_pastel = hsl("#D2A7DC"),
  purple_light = hsl("#994fb2"),
  purple_dark = hsl("#733381"),
  pink_pastel = hsl("#FCE8F4"),
  red = hsl("#F50000"),
  warn = hsl("#FCF4D4"),
  comment = hsl("#8C8C8C"),
}

local palette = {
  bg = colors.white,
  bg_subtle = colors.grays["800"],
  bg_very_subtle = colors.grays["700"],
  norm = colors.grays["000"],
  norm_subtle = colors.grays["100"],
  norm_very_subtle = colors.grays["200"],

  cursor_line = colors.grays["800"].lighten(60),
  comment = colors.comment,
  oob = colors.grays["900"],

  visual = colors.blue_pastel,
  literal = colors.green_dark,
  number = colors.blue,

  add = colors.green_pastel,
  change = colors.blue_pastel,
  delete = colors.red,

  error = colors.red,
  warn = colors.warn,
  hint = colors.green_dark,
  info = colors.grays["050"],
  ok = colors.norm_subtle,
  cursor_bg = colors.pink_pastel,
  match_paren = colors.blue_light,
}

return lush(function(injected_functions)
  local sym = injected_functions.sym
  -- stylua: ignore
  return {
  Normal { fg = palette.norm, bg = palette.bg },
	NormalFloat { fg = palette.norm, bg = palette.bg_subtle },
	NormalBorder { link = "NormalFloat" },

	Comment { fg = palette.comment, italic = true },
	SpecialComment { link = "Comment" },
	Critical { fg = palette.bg, bg = palette.accent, bold = true },

	-- constant literals
	Constant { fg = palette.norm },
	Character { link = "Constant" },
	Number { fg = palette.number, link = "Constant" },
	Boolean { link = "Constant" },
	Float { link = "Constant" },
	String {fg = palette.literal, link = "Constant" },
	Directory { link = "Constant" },
	Title { link = "Constant" },

	-- syntax
	Function { fg = palette.norm },
	Identifier { link = "Function" },

	Statement { bold = true },
	Conditonal { Statement },
	Repeat { Statement },
	Label { Statement },
	Keyword { Statement },
	Exception { fg = palette.error },

	PreProc { bold = true },
	Include { link = "PreProc" },
	Define { link = "PreProc" },
	Macro { link = "PreProc" },
	PreCondit { link = "PreProc" },

	Operator { fg = palette.accent },
	Debug { link = "Operator" },

	Special { italic = true },
	SpecialChar { link = "Special" },
	Tag { link = "Special" },
	Delimiter { link = "Special" },

	Underlined { underline = true },
	Ignore { fg = palette.norm_very_subtle },
	Error { reverse = true },
	Todo { fg = palette.accent, italic = true },

	-- spell
	SpellBad { undercurl = true },
	SpellCap { link = "SpellBad" },
	SpellLocal { link = "SpellBad" },
	SpellRare { link = "SpellBad" },

	-- ui
  Cursor { },
  CursorLine { bg = palette.cursor_line },
	ColorColumn { link = "CursorLine" },
	Conceal { link = "Comment" },
	CurSearch { link = "Visual" },
	CursorColumn { link = "CursorLine", },
	CursorLineNr { fg = palette.norm, bg = palette.cursor_line },
	EndOfBuffer { link = "Normal" },
	ErrorMsg { fg = palette.accent, bold = true },
	FloatBorder { fg = palette.norm_subtle, bg = palette.bg_subtle },
	FloatTitle {
		fg = palette.norm_subtle,
		bg = palette.bg_subtle,
		bold = true,
	},
	FoldColumn { fg = palette.bg_very_subtle },
	Folded { fg = palette.norm, bg = palette.bg_subtle, bold = true },
	LineNr { fg = palette.bg_very_subtle },
	MatchParen { bg = palette.match_paren },
	ModeMsg { fg = palette.norm, bold = true },
	MoreMsg { fg = palette.norm, bold = true },
	MsgArea { fg = palette.norm, bg = palette.bg_very_subtle },
	NonText { fg = palette.norm_very_subtle },
	NormalNC { link = "Normal" },
	NvimInternalError { link = "ErrorMsg" },
	Pmenu { bg = palette.bg_subtle },
	PmenoSbar { bg = palette.bg_subtle, reverse = true },
	PmenuKind { fg = palette.literal, bg = palette.bg_subtle },
	PmenuSel { fg = palette.norm, bg = palette.bg_subtle, reverse = true, bold = true },
	PmenuKindSel { fg = palette.literal, bg = palette.bg_subtle, reverse = true, bold = true },
	Question { bold = true },
	QuickFixLine { link = "Visual" },
	SignColumn { bg = palette.bg, fg = palette.norm, bold = true },
	SpecialKey { fg = palette.norm_subtle },
	StatusLine { fg = palette.norm, bg = palette.cursor_line },
	StatusLineNC { fg = palette.norm, bg = palette.oob, italic = true },
	StatusLineTerm { link = "StatusLine" },
	StatusLineTermNC { link = "StatusLineNC" },
	TabLine { fg = palette.norm_very_subtle, bg = palette.bg_very_subtle },
	TabLineFill { bg = palette.oob },
	TabLineSel { fg = palette.norm, bg = palette.bg, bold = true },
	Visual { bg = palette.visual },
	WarningMsg { fg = palette.critical, bold = true },
	WildMenu { link = "IncSearch" },
	WinBar { link = "StatusLine" },
	WinBarNC { link = "StatusLineNc" },
	WinSeparator { fg = palette.norm, bg = palette.bg },

	-- diagnostics
	DiagnosticDeprecated { strikethrough = true },

	DiagnosticError { fg = palette.error },
	DiagnosticWarn { fg = palette.norm },
	DiagnosticHint { fg = palette.comment },
	DiagnosticInfo { fg = palette.info  },
	DiagnosticOk { fg = palette.ok },

	DiagnosticUnderlineError { sp = palette.error, undercurl = true },
	DiagnosticUnderlineWarn { bg = palette.warn, sp = palette.warn, undercurl = true },
	DiagnosticUnderlineHint { sp = palette.hint, undercurl = true },
	DiagnosticUnderlineInfo { sp = palette.info, undercurl = true },
	DiagnosticUnderlineOk { sp = palette.norm, undercurl = true },

	DiagnosticVirtualTextError { DiagnosticError },
	DiagnosticVirtualTextHint { DiagnosticHint },
	DiagnosticVirtualTextInfo { link = "DiagnosticInfo" },
	DiagnosticVirtualTextWarn { link = "DiagnosticWarn" },

	DiagnosticDefaultError { link = "DiagnosticError" },
	DiagnosticDefaultHint { DiagnosticHint },
	DiagnosticDefaultInfo { link = "DiagnosticInfo" },
	DiagnosticDefaultWarn { link = "DiagnosticWarn" },

	DiagnosticFloatingError { link = "DiagnosticError" },
	DiagnosticFloatingHint { DiagnosticHint },
	DiagnosticFloatingInfo { link = "DiagnosticInfo" },
	DiagnosticFloatingWarn { link = "DiagnosticWarn" },

	DiagnosticSignError { link = "DiagnosticError" },
	DiagnosticSignHint { DiagnosticHint },
	DiagnosticSignInfo { link = "DiagnosticInfo" },
	DiagnosticSignWarn { link = "DiagnosticWarn" },

	-- git-related
	Added { fg = palette.add },
	Changed { fg = palette.change },
	Removed { fg = palette.delete },
	Deleted { fg = palette.delete },

	DiffAdd { link = "Added" },
	DiffChange { link = "Changed" },
	DiffDelete { link = "Removed" },
	DiffRemoved { link = "Removed" },

	DiffAddGutter { link = "Added" },
	DiffChangeGutter { link = "Changed" },
	DiffDeleteGutter { link = "Removed" },

	GitAdd { link = "Added" },
	GitChange { link = "Changed" },
	GitDelete { link = "Removed" },

	-- treesitter
	sym "@string.documentation" { link = "Comment" },
	sym "@keyword.function.julia" { bold = true },
  sym "@constant" { Constant },
  sym "@string" { String },

  Yank { bg = colors.yellow },
  Search {fg = palette.norm, bg = '#fcd47e' },     -- Last search pattern highlighting (see 'hlsearch')
  IncSearch { Search },                -- 'incsearch' highlighting; also used for the text replaced with ":s///c"
  Substitute { Search },               -- |:substitute| replacement text highlighting

	-- quickscope.vim 
	QuickScopeCursor { link = "Cursor" },
	QuickScopePrimary { link = "Search" },
	QuickScopeSecondary { link = "IncSearch" },

	-- mini.nvim 
	MiniStarterFooter { link = "Normal" },
	MiniStarterHeader { link = "Normal" },
	MiniStarterSection { link = "Normal" },
	-- gitsigns.nvim
	GitSignsAdd { link = "Added" },
	GitSignsChange { link = "Changed" },
	GitSignsDelete { link = "Removed" },
	GitSignsAddNr { link = "Added" },
	GitSignsChangeNr { link = "Changed" },
	GitSignsDeleteNr { link = "Removed" },
	GitSignsAddLn { link = "Added" },
	GitSignsChangeLn { link = "Changed" },
	GitSignsDeleteLn { link = "Removed" },
	-- telescope.nvim
	TelescopeSelection { link = "CursorLine" },
	-- whichkey.nvim
	WhichKey { link = "NormalFloat" },
	WhichKeyDesc { link = "WhichKey" },
	WhichKeyFloat { link = "WhichKey" },
	WhichKeyGroup { link = "Operator" },
	WhichKeyValue { link = "Operator" },
	WhichKeyBorder { link = "WhichKey" },
	WhichKeySeparator { link = "Constant" },
	-- oil.nvim
	OilDir { link = "Special" },
	OilCopy { link = "Function" },
	OilMove { link = "Function" },
	OilPurge { link = "Function" },
	OilTrash { link = "String" },
	OilChange { link = "Change" },
	OilCreate { link = "Add" },
	OilDelete { link = "Removed" },
	OilSocket { link = "Constant" },
	OilDirIcon { link = "OilDir" },
	OilRestore { link = "Function" },
	OilLinkTarget { link = "Underline" },
	OilTrashSourcePath { link = "Normal" },
	-- sidebar
	NormalSB { fg = palette.norm, bg = palette.oob },
	SignColumnSB { fg = palette.norm, bg = palette.oob },
	WinSeparatorSB { fg = palette.norm, bg = palette.oob },

  -- MiniCursorWord
  MiniCursorWord { bg = palette.cursor_bg },
  MiniCursorWordCurrent { bg = palette.cursor_bg },
  }
end)
